version: '3'
services:
  consul:
    image: 'hashicorp/consul'
    ports:
      - 8500:8500
  mysql:
    image: "mysql:8.0"
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=200489
    volumes:
      # 挂载初始化脚本
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      # 添加数据持久化
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
  redis:
    image: "redis:latest"
    ports:
      - 6379:6379
  nats:
    image: nats:latest
    ports:
      - "4222:4222"
      - "8222:8222"

# 挂载数据卷实现持久化存储
volumes:
  mysql_data:
    driver: local
