CREATE DATABASE IF NOT EXISTS user;
CREATE DATABASE IF NOT EXISTS cart;
CREATE DATABASE IF NOT EXISTS payment;
CREATE DATABASE IF NOT EXISTS checkout;
CREATE DATABASE IF NOT EXISTS product;
CREATE DATABASE IF NOT EXISTS order;

-- 设置字符集和排序规则
ALTER DATABASE user CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci;
ALTER DATABASE cart CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci;
ALTER DATABASE payment CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci;
ALTER DATABASE checkout CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci;
ALTER DATABASE product CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci; 
ALTER DATABASE order CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci;